module.exports = function (grunt) {

    // Project configuration.
    grunt.initConfig({

        // Get package information
        pkg: grunt.file.readJSON('package.json'),

        clean: {
            dist: {
                src: ['dist']
            },
            tmp: {
                src: ['tmp']
            }
        },

        jshint: {
            gruntfile: {
                src: ['Gruntfile.js']
            },
            dist: {
                src: ['src/index.js']
            }
        },

        uglify: {
            dist: {
                src: ['src/index.js'],
                dest: 'dist/index.js',
                options: {
                    preserveComments: false
                }
            }
        },

        inlinecss: {
            dist: {
                options: {

                },
                files: {
                    'tmp/email.html': 'src/email.html'
                }
            }
        },

        // Compress HTML
        htmlmin: {
            dist: {
                options: {
                    removeComments: true,
                    collapseWhitespace: true,
                    minifyCSS: true
                },
                files: {
                    'dist/email.html': 'tmp/email.html'
                }
            }
        },

        compress: {
            dist: {
                options: {
                    archive: '<%= pkg.name %>.zip',
                    mode: 'zip',
                    level: 9,
                    pretty: true
                },
                files: [
                    {
                        expand: true,
                        cwd: 'dist/',
                        src: ['**']
                    }
                ]
            }
        },

        // Watch tasks
        watch: {

            // If this file changes we need to reloaded
            // Furthermore it might be necessary to rebuild files that are generated by settings in here
            gruntfile: {
                files: ['Gruntfile.js'],
                tasks: ['jshint:gruntfile'],
                options: {
                    reload: true
                }
            },

            // Validate and compress Javascript on change
            js: {
                files: ['src/index.js'],
                tasks: ['jshint:dist', 'build'],
                options: {
                    interrupt: true
                }
            }
        }

    });

    // Load the plugins
    require('load-grunt-tasks')(grunt);

    grunt.registerTask(
        'build',
        'Make a clean build',
        ['clean', 'uglify:dist', 'inlinecss:dist', 'htmlmin:dist', 'compress:dist']
    );

};